@startuml

left to right direction

'DIAGRAM COLOR CODES
' New Component
!define GreenFillEis #A4CCAC
!define GreenStrokeEis #268742

' Modified Component
!define BlueFillEis #ADBBD2
!define BlueStrokeEis #002F56

' Unmodified Component
!define WhiteFillEis #FFFFFF
!define WhiteStrokeEis #666666

' Deprecated Component
!define RedFill #F7ABAB
!define RedStrokeEis #E83030

skinparam ranksep 50
skinparam linetype ortho

skinparam rectangle {
    BackgroundColor white
    BackgroundColor<<modified>> BlueFillEis
}


title F49908 : ELK Standardized Opinionated Templates Components  \n<color:#F7ABAB>**(New Proposed Design)**</color>

header: EPA.Stranger-Pings (2021-04-12)

footer: https://github.com/EBSCOIS/platform.infrastructure.elk/tree/master/docs

legend top right
    * New Component           = <color:#A4CCAC>**GREEN**</color>
    * Modified Component     = <color:#ADBBD2>**BLUE**</color>
    * Unmodified Component = <color:#FFFFFF>**WHITE**</color>
    * Deprecated Component = <color:#F7ABAB>**RED**</color>
end legend

caption Version 1.0

    rectangle "environmentManifest" as envmanrepo <<modified>> {
        rectangle envmanifest [
            <b>environment</b>
                ads
                <color:blue><b>ehost-devqa</b></color>
                |_ <b>BaseEnvironment</b>
                    |_ <color:blue><b>ServiceEndpoints.json (Global Level)</b></color>
                        |_ <back:yellow><b>redis</b></back>
                            - <back:yellow><b>address = logstash.ehost-devqa.eislz.com</b></back>
                            - <back:yellow><b>name =  redis </b></back>
                            - <back:yellow><b>port = 5044 </b></back>
                |_ <b>KVP</b>
                    |_ <color:blue><b>ExternalAgents (Global Level)</b></color>
                        |_ Filebeat
                            |_ centos7ami
                            |_ <b>windows2016ami</b>
                                |_ <back:yellow><b>InputJsonKeysUnderRoot = true</b></back>
                                |_ <back:yellow><b>InputJsonMessageKey = log</b></back>
                                |_ <back:yellow><b>InputPaths = c:\Logs\Service\Logstash\/transactions.log</b></back>
                                |_ <back:yellow><b>InputTags = filebeat</b></back>
                                |_ <back:yellow><b>InputType = log</b></back>
                                |_ <back:yellow><b>LoggingLevel = info</b></back>
                                |_ <back:yellow><b>OutputLogstashKey = logstash</b></back>
                                |_ <color:GreenStrokeEis><b>IndexTemplate<b> = log*</b></color>
                                |_ <color:GreenStrokeEis><b>VPC = ehost-devqa</b></color>
                    |_ <color:blue><b>Services (User Customized Level)</b></color>
                        |_ <b>af-admin-gateway-service</b>
                        |_ Agent
                            |_AppDynamics
                            |_ <b>Filebeat</b>
                                |_ <back:yellow><b><color:blue><b>InputPaths = C:\log4net\AdminGatewayService.log</color>
                                |_ <color:GreenStrokeEis><b>IndexTemplate = dotnet*</b></color>
                                |_ <color:GreenStrokeEis><b>InputTags = filebeat, ehost-devqa</b></color>
                            |_ Telegraf
                ehost-integration
                ehost-live-pi
                ehost-sigma
        ]
    }

    rectangle "EC2\nehost-devqa" as ec2 {
        rectangle "filebeat client" <<modified>> as filebeatcli {
            rectangle filebeatyml [
                filebeat.prospectors:
                - input_type: <back:yellow><b>log</b></back>
                paths:
                    - C:\log4net\HostNotifyProxy\HostNotifyProxy.log
                    - <back:yellow><b>C:\log4net\AdminGatewayService.log</b></back>
                <color:GreenStrokeEis><b>index_template: dotnet*</b></color>
                json.message_key: <back:yellow><b>log</b></back>
                json.keys_under_root: <back:yellow><b>true</b></back>
                tags: <color:GreenStrokeEis><b>[filebeat, ehost-devqa]</b></color>
                <color:GreenStrokeEis><b>vpc: ehost-devqa</b></color>
                - input_type: log
                paths:
                    - C:/ProgramData/consul/logs/consul-output.log
                fields:
                    category: consul_log
                    appname: consul
                    hosttype: webserver
                    program: consul.exe
                    retention: '30'
                exclude_lines: ["^DEBUG"]
                output.redis:
                hosts: <back:yellow><b>["logstash.ehost-devqa.eislz.com:5400"]</b></back>
                key: <back:yellow><b>logstash</b></back>
                logging.level: <back:yellow><b>info</b></back>

            ]
        }

        rectangle "Logfiles" as logfile
        ' add line sample from logfile w/new fields
        rectangle "ConsulAgent" as consulagent
        rectangle "ConsulTemplate\n\n  <b>filebeat.ctmpl</b>" as consultemplateEC2 <<modified>>
    }

    rectangle "platform.af.windows2016AIT" as win2016ait <<modified>> {
        rectangle "ConsulTemplate\n\n  <b>filebeat.ctmpl</b>" as consultemplateAIT
    }

    rectangle "Logstash" as logstash
    rectangle "elasticsearch" as elasticsearch

    consultemplateAIT  --|> consultemplateEC2
    consulagent <|--|> envmanifest
    consulagent --> consultemplateEC2
    consultemplateEC2 --> filebeatyml
    filebeatyml -down-|> logfile
    logfile -up-|> filebeatyml
    filebeatyml -right-|> logstash : PORT 5044
    logstash --> elasticsearch
@enduml
