@startuml

' left to right direction
skinparam maxMessageSize 50
skinparam packageStyle rectangle

<style>
usecase {
    HorizontalAlignment left
    MaximumWidth 20
}
</style>

title Victim and Type II Rescuer (Persecutor)

legend bottom left
    ' * TBD1 = <color:#ADBBD2>**BLUE**</color>
    ' * TBD2 = <color:#FFFFFF>**WHITE**</color>
    * Victim = <color:#LemonChiffon>**YELLOW**</color>
    * Type II Rescuer = <color:#A4CCAC>**GREEN**</color>
    * Victimizer/Persecutor = <color:#F7ABAB>**RED**</color>
end legend

' package dosingtrans as "
' Dissociative Dosing Transaction
' --
' Succesful dosing tranaction
' Percecutor 'insult or injury' <-exchange-> 'insult or injury' Victim
' * Both 'Players' in the game
' DISSOCIATE:
' -- more absent than present (unconscious - stupedied)
' -- more there then (regressed)
' -- less here now (present)
' "

' package dissociated as "
' Bodily Symptoms
' of Dissociation or Dissociated
' ..
' Hypoxic ==
' Hypercarbic ==
' Hypoglycemic ==

' "

' dosingtrans -down-> dissociated

' actor "Victim" as vic
' actor "Rescuer" as rescuer

' rectangle "Type II Rescuer\nPersonas" as T2Resc {
'     actor :Rescuer\n(Type II) : as rescue2 #palegreen;line:green;line.bold;text:green

'     actor/ :  Victimizer\n(Persecutor): as vicper #DarkRed;line:red;line.bold;text:red

'     rescue2 -down- vicper

' }

' rescuer -right-> rescue2
' rescuer -right-> vicper

' vic --> rescue2
' vic -down-> vicper

' vicper -down-> dosingtrans
    package theTrigger as "
        Trigger = Rescuer is agitated
        Event   = Starts moving furniture
                \taround hap-hazardly
        "
    rectangle "test" as test {
        actor "Victim" as victim3  << Hypervigilant >>
    }
    rectangle "test" as test2 {
        actor "Rescuer" as rescue3 << Agitated >>
    }

    usecase "Start" as start2 #palegreen;line:green;line.bold

    start2 -> rescue3
    ' theTrigger -down-> victim3
    rescue3 -right-> theTrigger
    theTrigger -right-> victim3
    victim3 -right-> vicStgHold
    ' vicStgHold -right-> resSiegeEngine
    ' victim3 -down-|> start2
    ' rescue3 -down-|> start2


' ======= VICTIM =========
rectangle "Victim \n(The Stronghold)" as vicStgHold {
    ' actor "Victim" as victim3  << Hypervigilant >>

        actor/ :  Victim: as vicDiag #palegreen;line:green;line.bold;text:green
    rectangle "Dialogs" as vicDiagBox {


        usecase "Can 'WE' move\n the furniture?" as dialog1
        usecase "I..I....\nyou are right" as dialog3
        usecase "I'm sorry,\n I'll isolate\n in my room" as dialog5

        dialog1 -down-|> dialog3 #line:green : counter response #1
        dialog3 -down-|> dialog5 #line:green : counter response #2

    }

    note left of vicDiag
    Victim :
    * Senses Agitation
    * Fear == Chaos
    * Chaos == Unsafe
    * Control == Safe
    * 'The Control' == Manipulation
    end note
}

' ======= RESCUER =========
rectangle "Rescuer \n(The Siege Engine)" as resSiegeEngine {
    ' actor "Rescuer" as rescue3 << Agitated >>


    ' usecase "Start" as start2 #palegreen;line:green;line.bold
    ' start2 -left-> rescue3

        actor/ :  Victimizer\n(Persecutor): as vicper #DarkRed;line:red;line.bold;text:red

    rectangle "Dialogs" as resDiag {


        usecase "Why would you\n EVER\n ask me that!" as dialog2
        usecase "This behavior\n of yours\n is trigger me!" as dialog4
        usecase "SIGHHHH..\nYour remind me\nof your sister Andrea\n (rolling eyes)" as dialog6

        dialog2 -down-|> dialog4 #line:white
        dialog4 -down-|> dialog6 #line:white

    }

    note left of vicper
    Rescuer :
    * Victim Conditions NOT
     met & emerges:
    * The Vicimizer
    end note


}

usecase "Dissociative Dosing Transaction\nCOMPLETE" as doseComplete

    vicDiag -right-> vicper #line:white

    vicDiag --> dialog1
    ' rescue3 --> dialog2 #line:white
    ' dialog1 -> vicper : 'Innocent' ask
    vicper --> dialog2

    dialog2 --> dialog1 #DarkRed;line:DarkRed;line.bold;text:DarkRed : insult
    dialog1 --> dialog2 #palegreen;line:green;line.bold;text:green : manipulation
    ' dialog2 --> dialog3 : annoyed response
    dialog4 --> dialog3 #DarkRed;line:DarkRed;line.bold;text:DarkRed : injury
    dialog3 --> dialog4 #palegreen;line:green;line.bold;text:green : manipulation

    ' dialog4 --> dialog5 : response
    dialog6 --> dialog5 #DarkRed;line:DarkRed;line.bold;text:DarkRed : injury
    dialog5 --> dialog6 #palegreen;line:green;line.bold;text:green : manipulation

    dialog5 -down-|> doseComplete #palegreen;line:green;line.bold;text:green



@enduml