@startuml

'hide footbox
skinparam ParticipantPadding 50
skinparam BoxPadding 20

skinparam roundcorner 20
skinparam backgroundColor #EEEBDC

skinparam sequence {
	ArrowColor #0e477d
	ActorBorderColor DeepSkyBlue
	LifeLineBorderColor blue
	LifeLineBackgroundColor #A9DCDF
	
	ParticipantBorderColor LightSteelBlue
	ParticipantBackgroundColor Gray
	ParticipantFontSize 17
	ParticipantFontColor White
}

    header F37043_sequence_ui_af_secrets_diagram.wsd
    footer Page %page% of %lastpage%

    title F37043 : AF Secrets - Sequence Diagram

    participant "UI \naf-jenkins\n(onprem)" as ui
    participant "CDF \n(onprem)" as cdflib
    participant "SSM \n Parameter Store \n(aws)" as ssm
    participant "Stash \n(onprem)" as stash
    participant "Consul \n(onprem)" as consul
    participant "Consul Template\n(P9)" as consul_temp
    participant "ACL\n(P9)" as acl
    
    'participant "Open Stack P9 \n(onprem)" as p9

==UI : Create New PEM Key==
    ui -> cdflib : Create PEM Key
    cdflib -> ssm++ : Copy PEM key to SSM
        rnote right of ssm #fc8c03
            <b>SSM PEM Keys Stored :</b>
            # By ADE, by Service
            # (optional) : make PEM backup to S3   
        end note
    ssm -> ssm 
    ui <-- ssm-- : Pass / Fail

==UI : Add/Update Secrets==
    ui -> cdflib : Dev : Add/Update Secret
    cdflib -> ssm++ : Get PEM Key
    cdflib <-- ssm--

    cdflib -> stash++  : Encrypt Secret & Create PR
        rnote right of stash #fc8c03
        <b>Steps :</b>
        # Create Feature branch
        # Update EnvironmentManifest
        end note
    stash -> stash 
    ui <-- stash-- : Pass / Fail

==OpenStack : Deploy PEM Key== 
    cdflib -> ssm++ : Get PEM key from SSM
    cdflib <-- ssm--
    cdflib -> acl++ : PyOrc : Copy PEM key to P9
    cdflib <-- acl-- : Pass / Fail

==OpenStack : Decrypt Secret== 
    stash -> consul : PR Merged
    consul -> consul_temp : Consul Change Event
    consul_temp -> acl++ : Update Config files
        rnote right of acl #fc8c03
        <b>Steps :</b>
        # Decrypt Secrets w/local PEM key
        # AppConfig updated w/secret
        end note

@enduml
