
'Component Diagram Acceptance Criteria :
'https://confluence.epnet.com/x/QJXHE

@startuml

skinparam componentStyle rectangle
skinparam fontsize 10
skinparam StereotypeFontSize 10
skinparam roundCorner 20

skinparam DatabaseBackgroundColor #FFFFFF
skinparam FileBackgroundColor #FFFFFF
skinparam InterfaceBackgroundColor #FFFFFF
skinparam NodeBackgroundColor #FFFFFF
skinparam RectangleBackgroundColor #FFFFFF
skinparam QueueBackgroundColor #FFFFFF

skinparam legend {
    FontSize 20
    BorderThickness 4
}

skinparam title {
    BorderRoundCorner 10
    BorderThickness 2
    titleBorderColor DimGray
    titleFontSize 60
}

title ELK AWS LZ  <color:#F7ABAB>**(Current Design)**</color>

header: EPA.Stranger-Pings (2021-03-24)

footer: https://github.com/EBSCOIS/platform.infrastructure.elk/tree/master/docs

legend bottom left
    * New Component           = <color:#A4CCAC>**GREEN**</color>
    * Modified Component     = <color:#ADBBD2>**BLUE**</color>
    * Unmodified Component  = <color:#FFFFFF>**WHITE**</color>
    * Deprecated Component = <color:#F7ABAB>**RED**</color>
end legend

caption Version 1.0

rectangle "eis-lz-shared-devqa" <<Account>> as acctSharedDevQa {

    rectangle "shared-devqa" <<VPC>> as vpcSHQ {

        node "EC2" <<Service>> as ec2SHQ {

            component "Filebeat" as fbSHQ {

                file "filebeat.yaml" as fbyamlSHQ
            }
        }

        interface "Data Flow" as dataEntrySHQ
        dataEntrySHQ -down-> fbyamlSHQ

        rectangle "\tELK\n\tNOT\nIMPLEMENTED" as noElkSHQ
        fbyamlSHQ --> noElkSHQ
    }

    interface "Entry\nPoint" as dataEntrySharedDevQa
    dataEntrySharedDevQa --> dataEntrySHQ
}

rectangle "eis-lz-shared" <<Account>> as acctShared {

    rectangle "shared" <<VPC>>  as vpcSH {

        node "EC2" <<Service>>  as ec2SH {

            component "Filebeat" as fbSH {

                file "filebeat.yaml" as fbyamlSH
            }
        }

        interface "Data Flow" as dataEntrySH
        dataEntrySH -down-> fbyamlSH

        rectangle "\tELK\n\tNOT\nIMPLEMENTED" as noElkSH
        fbyamlSH --> noElkSH
    }

    interface "Entry\nPoint" as dataEntryShared
    dataEntryShared --> dataEntrySH
}

rectangle "eis-lz-ehost-devqa" <<Account>> as acctEhostDevQa {

    rectangle "ehost-devqa" <<VPC>>  as vpcQ {

        node "EC2" <<Service>> as ec2Q {

            component "Filebeat" as fbQ {

                file "filebeat.yaml" as fbyamlQ
            }
        }

        rectangle " " <<Logstash>> as lsQ  {

            component lsNlbQ as "
            \tElastic Load Balancer
            --
            <b>logstash.ehost-devqa.eislz.com</b>
            "

            node "EC2\nC4.xlarge" <<Logstash>> as ls2Q {

                queue "In-Memory\n  Queue" as pq2Q
            }

            node "EC2\nC4.xlarge" <<Logstash>> as ls1Q {

                queue "In-Memory\n  Queue" as pq1Q
            }
        }

        rectangle "<b>Domain : es-centralizedlogging</b>" <<Elasticsearch Cluster (Managed)>> as escQ {

            component kibanaQ <<kibana>> as "
            \t\tKibana UI
            --
            <b>http:\\elk.ehost-devqa.eislz.com</b>
            "

            component elasticEndpointQ <<endpoint>> as "
            Elasticsearch Endpoint
            --
            <b>elk.ehost-devqa.eislz.com</b>
            "

            rectangle "Master Nodes" as masterQ {
                node "  Master\nC5.xlarge" <<elasticsearch>>  as mn3Q
                node "  Master\nC5.xlarge" <<elasticsearch>>  as mn2Q
                node "  Master\nC5.xlarge" <<elasticsearch>>  as mn1Q
            }

            rectangle "Data Nodes" as dataQ {
                database "  Data\nC5.xlarge" <<elasticsearch>> as dn1Q
                database "  Data\nC5.xlarge" <<elasticsearch>> as dn2Q
                database "  Data\nC5.xlarge" <<elasticsearch>> as dn3Q
                database "  Data\nC5.xlarge" <<elasticsearch>> as dn4Q
                database "  Data\nC5.xlarge" <<elasticsearch>> as dn5Q
                database "  Data\nC5.xlarge" <<elasticsearch>> as dn6Q
            }

            interface "  Kibana\nEntry Point " as kibanaEntryQ
            kibanaEntryQ -left-> kibanaQ

            kibanaQ -left-> elasticEndpointQ

            elasticEndpointQ --> mn3Q
            elasticEndpointQ --> mn2Q
            elasticEndpointQ --> mn1Q

            dataQ --> dn6Q
            dataQ --> dn5Q
            dataQ --> dn4Q
            dataQ --> dn3Q
            dataQ --> dn2Q
            dataQ --> dn1Q

            mn3Q --> dataQ
            mn2Q --> dataQ
            mn1Q --> dataQ
        }

        fbyamlQ -down-> lsNlbQ
        lsNlbQ --> pq1Q
        lsNlbQ --> pq2Q
        pq1Q --> elasticEndpointQ
        pq2Q --> elasticEndpointQ

        interface " " as dataEntryQ
        dataEntryQ -down-> fbyamlQ
    }

    interface "Entry\nPoint" as dataEntryEhostDevQa
    dataEntryEhostDevQa --> dataEntryQ
}

rectangle "eis-lz-ehost-integration" <<Account>> as acctEhostInt {

    rectangle "ehost-int" <<VPC>>  as vpcI {

        node "EC2" <<Service>> as ec2I {

            component "Filebeat" as fbI {

                file "filebeat.yaml" as fbyamlI
            }
        }

        interface "Data Flow" as dataEntryI
        dataEntryI -down-> fbyamlI

        rectangle "\tELK\n\tNOT\nIMPLEMENTED" as noElkI
        fbyamlI --> noElkI
    }

    interface "Entry\nPoint" as dataEntryEhostInt
    dataEntryEhostInt --> dataEntryI
}

rectangle "eis-lz-ehost-live" <<Account>> as acctEhostLive {

    rectangle "ehost-live-sigma" <<VPC>>  as vpcSi {

        node "EC2" <<Service>> as ec2Si {

            component "Filebeat" as fbSi {

                file "filebeat.yaml" as fbyamlSi
            }
        }

        interface " " as dataEntrySi
        dataEntrySi -down-> fbyamlSi
    }

    rectangle "ehost-live-pi" <<VPC>>  as vpcPi {

        node "EC2" <<Service>> as ec2Pi {

            component "Filebeat" as fbPi {

                file "filebeat.yaml" as fbyamlPi
            }
        }

        rectangle " " <<Logstash>> as lsPi {

            component lsNlbPi as "
            \tElastic Load Balancer
            --
            <b>logstash.ehost-live.eislz.com</b>
            "

            node "EC2\nC4.xlarge" <<Logstash>> as ls1Pi {

                queue "In-Memory\n  Queue" as pq1Pi
            }

            node "EC2\nC4.xlarge" <<Logstash>> as ls2Pi {

                queue "In-Memory\n  Queue" as pq2Pi
            }
        }

        rectangle "<b>Domain : es-centralizedlogging</b>" <<Elasticsearch Cluster (Managed)>> as escPii {

            component kibanaPi <<kibana>> as "
            \t\tKibana UI
            --
            <b>http:\\elk.ehost-live.eislz.com</b>
            "

            component elasticEndpointPi <<endpoint>>  as "
            Elasticsearch Endpoint
            --
            <b>elk.ehost-live.eislz.com</b>
            "

            rectangle "Master Nodes" as masterPi {

                node "  Master\nC5.xlarge" <<elasticsearch>>  as mn3Pi
                node "  Master\nC5.xlarge" <<elasticsearch>>  as mn2Pi
                node "  Master\nC5.xlarge" <<elasticsearch>>  as mn1Pi
            }

            rectangle "Data Nodes" as dataPi {

                database "  Data\nC5.xlarge" <<elasticsearch>> as dn1Pi
                database "  Data\nC5.xlarge" <<elasticsearch>> as dn2Pi
                database "  Data\nC5.xlarge" <<elasticsearch>> as dn3Pi
                database "  Data\nC5.xlarge" <<elasticsearch>> as dn4Pi
                database "  Data\nC5.xlarge" <<elasticsearch>> as dn5Pi
                database "  Data\nC5.xlarge" <<elasticsearch>> as dn6Pi
            }

            interface "  Kibana\nEntry Point " as kibanaEntryPi
            kibanaEntryPi -left-> kibanaPi

            kibanaPi -left-> elasticEndpointPi

            elasticEndpointPi --> mn3Pi
            elasticEndpointPi --> mn2Pi
            elasticEndpointPi --> mn1Pi

            dataPi --> dn6Pi
            dataPi --> dn5Pi
            dataPi --> dn4Pi
            dataPi --> dn3Pi
            dataPi --> dn2Pi
            dataPi --> dn1Pi

            mn3Pi --> dataPi
            mn2Pi --> dataPi
            mn1Pi --> dataPi
        }

        fbyamlPi -down-> lsNlbPi
        fbyamlSi -down-> lsNlbPi
        lsNlbPi --> pq1Pi
        lsNlbPi --> pq2Pi
        pq1Pi --> elasticEndpointPi
        pq2Pi --> elasticEndpointPi

        interface " " as dataEntryPi
        dataEntryPi -down-> fbyamlPi
    }

    interface "Entry\nPoint" as dataEntryEhostLive
    dataEntryEhostLive --> dataEntryPi
    dataEntryEhostLive --> dataEntrySi
}

@enduml