@startmindmap

' <&name> = creole open iconic icons : https://useiconic.com/open/

'--------STYLING---------
<style>
mindmapDiagram {
  .green {
    BackgroundColor lightgreen
  }
  .asChild {
    BackgroundColor Yellow
  }
  .asAdult {
    BackgroundColor lightblue
  }
}
</style>

'--------MINDMAP---------

* <&star>Trait6

'-------The Laundry List-------
**: <&circle-x>
===\t\t\tThe Laundry List
"<u:red>We have an overdeveloped sense of responsibility</u>"

# It is <back:Yellow><u>easier</u></back> (//"necessary"//) for us to be
concerned with others rather than ourselves

# This enables us not to look too closely
at our own faults, etc.;

***:===As Children
====Magical Powers
* natural belief we are omnipotent
* child cries and caregiver appears
** Belief :  crying == produces caregiver (magically)
* Magical powers are overused to give normalcy in chaotic family
** family acts crazily
*** magical powers (crying) could control them
*** became responsible to control them even though
         it was not our responsibility and was beyond our control.
*** Try to treat the symptom(the action/behavior)
          not problem(alcoholism)
* **Rescuer Role** (emerges)
|_ As Victim or
|_ As Victimzer
|= Internal Dosing |= Effect    |
| Adrenaline      | Excitement |
| Cortisol        | Worry      |
|                 | Internal Speeedball|
;<<asChild>>

****:==As Adults
The Tactic (rescuer role) became a "Habit" to:
* __ALWAYS__ "assume" over-responsibility for others (insert myself)
** __WHY__ : because it gave us an excuse not look at ourselves

<back:MistyRose>Why not look at ourselves?</back>
* discomfort of "honestly" looking at our pain and losses
* unexpressed feeling and memories from tramatic childhood has
   festered to the point its to BIG for "ME" to control
* when examined, almost always looking destructively and in
   a self-critical manner.
* dont know how to look at ourselves in a constructive way


**"Habit" (over) "Honesty"**

| Looking at self => discomfort & pain(depression/sadness) =>\n Being "responsible" and "helpful" to others (aka rescuer role) =>\n Replaces "discomfort" with internal dosing of "worry" & "excitement" =>\n "Responsible" and "Helful" to others distracts from =>\n "Healing" my True Self |

;<<asAdult>>

***:===As Children
====Necessary ==> Hypervigilance
* __Hypervigilance__ made it __necessary__ for us as
 children to focus on others so that we could __survive__

* **__"Hypervigilantly" survey__**:
|_ our thoughts and actions to feel safe **
|_ our parent’s tone of voice, body language and gestures
|_ others comments, emotions, actions and reactions
|_ our surroundings and environment for threats

<back:MistyRose>**TODO: Search BRB for "Hypervigilance" examples (list)**</back>

Adult children dread emotional pain because we rarely
had anyone to stand with us as we experienced anguish
as children. Growing up in a dysfunctional home,
we often endured unspeakable suffering in silence.
We became hypervigilant to emotional pain and sought
addiction, work, sex, or drugs to stay “pain” free.

BRB (p. 236). ACA WSO INC.. Kindle Edition.

;<<asChild>>
****:===As Adult
<back:MistyRose>**As an Adult HOW do I "Hypervigilantly survey"?**</back>
* <make a list>
;<<asAdult>>

***:===As Children
==== Definition:  "Hypervigilance"
* Can be a <w>symptom</w> of PTSD
* Unusually sensitive to:
| the environment | the people around them |

* The subconscious is constantly anticipating danger.
* As a result, their senses are on high alert
  ready to spot and respond to danger such as:
| a physical danger | repeat of a traumatic event|
| feel as though there is always\n a threat around the corner | something wrong in a relationship |;<<asChild>>


****_ **Symptoms**
***** "Physical"
******:
| dilated pupils      | breathing very quickly |
| seeming restless ** | sweating **            |
| rapid heart beat ** |                        |;
***** "Behavioral"
******:
| keep checking their surroundings                            | find it hard to focus on conversations          |
| trouble getting to sleep or staying asleep                  | find crowded or noisy environments overwhelming |
| look closely at people to see if they are\n holding weapons | be easily startled and jump or scream at things\n they hear or see suddenly |
| overanalyze situations and believe them to\n be worse than they are| be overly sensitive to people’s tone\n or expressions, taking them personally |
| overreact to things happening around them in\n a way that may seem hostile | overestimate the chances of a bad thing\n happening to them physically or in their relationships |;
***** "Complications\n (Long-term)"
******:
| difficulty in relationships     | physical and mental exhaustion |
| problems in the workplace       | obsessive behavior patterns    |
| avoidance of social situations  |                                |;

****_ **Causes**
***** "Anxiety"
***** "PTSD"
******:
<back:MistyRose>What are my PTSD triggering events?</back>
* expressed in our hypervigilance of our surroundings
  or our acute monitoring of comments or actions of
  others. This behavior is a carry-over from growing
  up on guard much of the time.

As and Adult:
* Im constantly monitoring my thoughts and actions..to
  make the right decision, say right thing, to avoid
  or not draw threats towards me
;<<asAdult>>

***** "Triggers"
******:
| feeling claustrophobic **       | criticism or embarrassment **        |
| crowded environments  **        | competing demands or expectations ** |
| uncertain situations **         | chaotic behavior by others **        |
| reminders of past trauma **     | feeling as if they have been  abandoned ** |
| arguments and shouting **       | feeling or anticipating pain **      |
| being emotionally distressed ** |                                      |;

****_ **Detection**
*****:
table of trigger => feeeling -> mental & physical
;<<asAdult>>


***:===As Children
* As children we were completely busy
looking outward to survive
;<<asChild>>

'-------The Other Laundry List-------

**: <&circle-x>
===\tThe Other Laundry List
"<u:red>We are irresponsible and self-centered..</u>"

* Our inflated sense of self-worth and
self-importance prevents us from seeing
our <u>deficiencies</u> and <u>shortcomings</u>.
;
***_ Dissociate from our responsibilities
****:
* "The sheer weight of ALL that responsibility becomes too much
to bear, we then go in the opposite direction"
* TODO :
** List out what resposibilites become too much to bear?
** What does this look like?
; <<asAdult>>

***_ Become engrossed in our false self
**** What is our False Self? <<asAdult>>
****_ What is important to others is NO LONGER matters to us
***** Why doesnt it not matter to us? <<asAdult>>
****_ we strategize, if people just took care of themselves everybody would be okay
***** TODO : List examples of this as an Adult today <<asAdult>>

***_ Increase level of false self attention
****_ Worsens over time
****_ Alienates those around us
***** How in this mind set do we alienate others? <<asAdult>>
*****:
The experience of being powerless to control the events
that damage us as children leaves us with a deep feeling
of alienation, not only from others, but from our own
openness and vulnerability as well.
BRB(p. 371). ACA WSO INC.. Kindle Edition.
;

***_ Armed with false self-importance
****_ We act out on our loved ones, co-workers and friends
****_ The deficiencies and shortcomings we suffered from our childhood
***** What are those deficiencies and shortcomings we suffered?  <<asAdult>>
**** What does self-importance look like?  <<asAdult>>

***_ Our false self-centeredness
****_ keeps us blind to our deficiencies and shortcomings
***** What are mydeficiencies and shortcomings? <<asAdult>>
****_ when standing too close to our defensive false-self
***** How is my false-self actig defensively? <<asAdult>>








'==========LEFT SIDE=================

left side

'-------The Flip Side of The Laundry List-------
**: <&circle-check>
===The Flip Side of The Laundry List

"We do not use <u>enabling</u> as a way to avoid
 looking at <u>our</u> own <u>shortcomings</u>"
;

'-------The Flip Side of The Other Laundry List-------
**: <&circle-check>
===The Flip Side of The Other Laundry List

"Through our <u>in-depth inventory</u> we discover
 our <u>true identity</u> as <u>capable<u>, <u>worthwhile</u> people."

* By asking to have our shortcomings removed
* we are <u>freed</u> from the <u>burden</u> of:
** <u>inferiority</u> and
** <u>grandiosity</u>
;

'==========TITLE============
caption figure 1
title ACA - Trait 6

header
My ACA - Trait 6
endheader

center footer My ACA - Trait 6

legend left
  Short legend
endlegend
@endmindmap