/' URLS:
    https://www.augmentedmind.de/2021/01/03/plantuml-tutorial-diagrams-as-code/

    http://plantuml.com/guide

    https://forum.plantuml.net/search?q=cannot+find+height

  COLOR LOOKUP:
    https://www.colorhexa.com/

  ** USE THIS SITE **
  ICON Websites Download PNG Images
    https://materialdesignicons.com/  ***letters and numbers
      1. Click on icon
      2. Click on "Icon" button (lower righthand)
      3. Select == '.PNG 48 white"
      4. Download image to directory inside PlantUML source

  ** NEED TO RESEARCH THESE SITES **
    ICONS - OTHER
    https://fontawesome.com/start
    https://github.com/Templarian/MaterialDesign/tree/master/svg

  TODO:
    1. Try to get svg to work? maybe?
'/

@startuml

' See Hitchhiker Guide for 'Arrows' POLYLINE & ORTHO
' skinparam linetype polyline
skinparam linetype ortho

allow_mixing

/'

Only need images whtite, size 48 outline. Color and scale can be changed in plantUML using creole.
'/
sprite mySpriteAlphaA \ACA_example\png\alpha-a-circle-outline-wht-48.png
sprite mySpriteAlphaB \ACA_example\png\alpha-b-circle-outline-wht-48.png
sprite mySpriteAlphaC \ACA_example\png\alpha-c-circle-outline-wht-48.png
sprite mySpriteAlphaD \ACA_example\png\alpha-d-circle-outline-wht-48.png
sprite mySpriteAlphaE \ACA_example\png\alpha-e-circle-outline-wht-48.png
sprite mySpriteAlphaF \ACA_example\png\alpha-f-circle-outline-wht-48.png

sprite mySpriteNum1 \ACA_example\png\numeric-1-circle-outline-wht-48.png
sprite mySpriteNum2 \ACA_example\png\numeric-2-circle-outline-wht-48.png
sprite mySpriteNum3 \ACA_example\png\numeric-3-circle-outline-wht-48.png
sprite mySpriteNum4 \ACA_example\png\numeric-4-circle-outline-wht-48.png
sprite mySpriteNum5 \ACA_example\png\numeric-5-circle-outline-wht-48.png
sprite mySpriteNum6 \ACA_example\png\numeric-6-circle-outline-wht-48.png


' <img:file> : the file must be accessible by the filesystem
' < > : the URL must be available from the Internet



rectangle "<$mySpriteTestB>" as rectB

card "<$mySpriteTestC>\n <$mySpriteTestC>" as test {

}


card vicdetails<<victim>> as "

<img:http://plantuml.com/logo3.png{scale=0.5}>
--

Test variable with image
<color:blue><$mySpriteTestB{scale=1}></color> 'Blue'
<color:Aliceblue><$mySpriteTestB{scale=1}></color> 'Aliceblue'
<color:#8b0000><$mySpriteTestB{scale=.5}></color> 'DarkRed Hex'
<color:darkred><$mySpriteTestA{scale=.25}></color> 'DarkRed plantuml'
<color:darkred><$mySpriteTestA{scale=1}></color> 'DarkRed plantuml'

<color:#8b0000><$mySpriteTestCscale=.5}></color> <color:blue><$mySpriteTestC{scale=.5}></color>
<$mySpriteTestD>
<$mySpriteTestD>



"
' using img: can adjust scale but NOT color need to have png pre-colored
test -right-> vicdetails

rectB -up-> test : <color:darkred><$mySpriteTestA{scale=1}></color> \n<$mySpriteTestD> \n<$mySpriteTestC>


@enduml